version: '3.7'
services:
  web:
    build:
      context: .
    env_file: envs/.env
    restart: always
    command: sh -c "gunicorn developers_today.wsgi -b 0.0.0.0:8000"
    depends_on:
     - db
    environment:
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
  worker_huey:
    build:
      context: .
    env_file: envs/.env
    restart: always
    command: sh -c "python manage.py run_huey"
    depends_on:
      - web
  db:
    image: postgres:13.3
    env_file: envs/.env
  redis:
    image: redis:6.2.6-alpine
    env_file: envs/.env
